!ifndef COMPONENTS
!include ../../../Templates/Components.cuml
!endif

module(keystroke_linux) {
    function(ReadSTDIN_NonBlocking_Linux)
    
    class(InputBufferLinux)
    
    InputBufferLinux <-- ReadSTDIN_NonBlocking_Linux
    
    class(KeyboardListenerLinux)
    
    InputBufferLinux *-- KeyboardListenerLinux
}