@startuml sudoku_ui_cli_keystroke_linux_inputbufferlinux_isready

title Activity Diagram of the Property InputBufferLinux.IsReady

start

if (data timer has expired?) then (True)
    :purge the buffer;
    
    :reset the data timer;
endif

if (is there still data in the buffer?) then (Yes)
    :return True>
else (No)
    :return False>
endif

stop

@enduml