@startuml sudoku_ui_cli_components

title Components Diagram of the Sub-Package ui.cli

!ifndef COMPONENTS
!include ../../Templates/Components.cuml
!endif

package(cli) {
    !ifndef UI_CLI_TERMINAL_SIZE
    !include ./terminal_size/sudoku_ui_cli_terminal_size_components.iuml
    !endif
    
    !ifndef UI_CLI_KEYSTROKE_WINDOWS
    !include ./keystroke_windows/sudoku_ui_cli_keystroke_windows_components.iuml
    !endif
    
    !ifndef UI_CLI_KEYSTROKE_LINUX
    !include ./keystroke_linux/sudoku_ui_cli_keystroke_linux_components.iuml
    !endif
    
    !ifndef UI_CLI_TERMINAL_UTILS
    !include ./terminal_utils/sudoku_ui_cli_terminal_utils_components.iuml
    !endif
    
    KeyboardListenerLinux <-- GetKeystroke
    
    KeyboardListenerWindows <--- GetKeystroke
    
    GetTerminalSize <--- PrintLess
    
    GetTerminalSize <--- ClearConsole
    
    !ifndef UI_CLI_BASIC_UI_ELEMENTS
    !include ./basic_ui_elements/sudoku_ui_cli_basic_ui_elements_components.iuml
    !endif
    
    GetKeystroke <--- SimpleMenuCLI
    
    PrintFW <--- SimpleMenuCLI
    
    ClearConsole <--- SimpleMenuCLI
    
    !ifndef UI_CLI_USER_MENUS
    !include ./user_menus/sudoku_ui_cli_user_menus_components.iuml
    !endif
    
    SimpleMenuCLI <|--- MainMenu
    
    SimpleMenuCLI <|--- HelpMenu
}

@enduml