@startuml

title Class Diagram of the Module ui.cli.keystroke_linux

namespace threading {
    class Event
    
    class Thread
}

!ifndef UI_CLI_KEYSTROKE_LINUX_KEYBOARDLISTENERLINUX
!include ./KeyboardListenerLinux.iuml
!endif

!ifndef UI_CLI_KEYSTROKE_LINUX_INPUTBUFFERLINUX
!include ./InputBufferLinux.iuml
!endif

threading.Event "1" *-- "1" KeyboardListenerLinux

threading.Thread "1" *-- "1" KeyboardListenerLinux

KeyboardListenerLinux "1" -* "1" InputBufferLinux 

@enduml