!define UI_CLI_KEYSTROKE_LINUX_INPUTBUFFERLINUX

!ifndef CLASSES
!include ../../../Templates/Classes.cuml
!endif

class InputBufferLinux {
    # _strOutBuffer: unicode
    # _dLastTime: double
    + IsReady: bool
    __
    + _ _init_ _(): None -> None
    + put(): str OR unicode -> None
    + get(): None -> unicode OR None
}