@startuml

title Activity Diagram of the Method InputBufferLinux.put()

start

:<b>InData</b> - string, supposedly unicode<

:remove previously stored data from the buffer;

:copy <b>InData</b> as unicode into the buffer;

:reset the data timer;

stop

@enduml